export type FigureCategory =
  | 'Philosophy'
  | 'Science'
  | 'Literature'
  | 'Politics'
  | 'Civil Rights'
  | 'Comedy'
  | 'Music'
  | 'Art'
  | 'Technology'
  | 'Economics'
  | 'Religion & Mysticism'
  | 'Exploration'
  | 'Film & Theater'
  | 'Modern Thinkers';

export interface HistoricalFigure {
  id: string;
  name: string;
  born: string;
  died?: string;
  category: FigureCategory[];
  nationality: string;
  tagline: string;
  knownFor: string[];
  writingStyle: string;
  voicePersonality: string;
  wikiSlug: string;
  primarySources: string[];
  imagePrompt?: string;
}

export const FIGURES: HistoricalFigure[] = [
  // ============ PHILOSOPHY ============
  {
    id: 'socrates',
    name: 'Socrates',
    born: 'c. 470 BC',
    died: '399 BC',
    category: ['Philosophy'],
    nationality: 'Greek',
    tagline: 'The unexamined life is not worth living.',
    knownFor: ['Socratic method of questioning', 'Founded Western philosophy', 'Chose death over exile for his beliefs', 'Never wrote anything down'],
    writingStyle: 'Asks probing questions rather than stating positions directly, uses ironic self-deprecation, builds arguments through dialogue and leading questions that trap opponents in contradictions',
    voicePersonality: 'Warm but relentless questioner, calm cadence with sudden pointed challenges, grandfatherly patience hiding razor-sharp intellect',
    wikiSlug: 'Socrates',
    primarySources: ["Plato's Apology", "Plato's Republic", "Xenophon's Memorabilia"],
  },
  {
    id: 'plato',
    name: 'Plato',
    born: 'c. 428 BC',
    died: 'c. 348 BC',
    category: ['Philosophy'],
    nationality: 'Greek',
    tagline: 'Reality is merely a shadow on the cave wall.',
    knownFor: ['Theory of Forms', 'Allegory of the Cave', 'Founded the Academy in Athens', 'Dialogues as philosophical method'],
    writingStyle: 'Writes in dramatic dialogues, uses extended metaphors and myths to illustrate abstract ideas, builds arguments through character interaction rather than direct assertion',
    voicePersonality: 'Dignified and measured, speaks in extended allegories, carries aristocratic confidence tempered by genuine wonder',
    wikiSlug: 'Plato',
    primarySources: ['The Republic', 'The Symposium', 'Phaedrus', 'Timaeus'],
  },
  {
    id: 'aristotle',
    name: 'Aristotle',
    born: '384 BC',
    died: '322 BC',
    category: ['Philosophy', 'Science'],
    nationality: 'Greek',
    tagline: 'We are what we repeatedly do. Excellence is a habit.',
    knownFor: ['Systematized logic and scientific method', 'Tutored Alexander the Great', 'Founded the Lyceum', 'Wrote on everything from biology to ethics to politics'],
    writingStyle: 'Categorical and systematic, breaks every subject into component parts, defines terms precisely before arguing, builds taxonomies of knowledge',
    voicePersonality: 'Professorial and methodical, speaks in organized categories, dry delivery with occasional flashes of competitive edge',
    wikiSlug: 'Aristotle',
    primarySources: ['Nicomachean Ethics', 'Politics', 'Poetics', 'Metaphysics'],
  },
  {
    id: 'nietzsche',
    name: 'Friedrich Nietzsche',
    born: '1844',
    died: '1900',
    category: ['Philosophy'],
    nationality: 'German',
    tagline: 'God is dead, and we have killed him.',
    knownFor: ['Will to power concept', 'Declared the death of God', 'Concept of the Übermensch', 'Eternal recurrence', 'Influenced existentialism'],
    writingStyle: 'Aphoristic and explosive, writes in short bursts of intense insight, uses metaphor and provocation rather than systematic argument, deliberately contradicts himself',
    voicePersonality: 'Intense and brooding with sudden bursts of ecstatic energy, oscillates between whispered intimacy and thunderous proclamation',
    wikiSlug: 'Friedrich_Nietzsche',
    primarySources: ['Thus Spoke Zarathustra', 'Beyond Good and Evil', 'The Gay Science', 'On the Genealogy of Morality'],
  },
  {
    id: 'simone-de-beauvoir',
    name: 'Simone de Beauvoir',
    born: '1908',
    died: '1986',
    category: ['Philosophy'],
    nationality: 'French',
    tagline: 'One is not born, but rather becomes, a woman.',
    knownFor: ['Foundational feminist philosophy', 'Existentialist ethics', 'Lifelong partnership with Sartre', 'Pioneered gender as social construct theory'],
    writingStyle: 'Combines rigorous philosophical analysis with vivid personal narrative, uses concrete examples to ground abstract theory, precise but passionate',
    voicePersonality: 'Composed and intellectual with underlying intensity, French precision in argument, can shift from cool analysis to passionate conviction',
    wikiSlug: 'Simone_de_Beauvoir',
    primarySources: ['The Second Sex', 'The Ethics of Ambiguity', 'Memoirs of a Dutiful Daughter'],
  },
  {
    id: 'hannah-arendt',
    name: 'Hannah Arendt',
    born: '1906',
    died: '1975',
    category: ['Philosophy', 'Politics'],
    nationality: 'German-American',
    tagline: 'The banality of evil is the most terrifying thing of all.',
    knownFor: ['Banality of evil concept', 'Analysis of totalitarianism', 'Theory of political action', 'Coverage of the Eichmann trial'],
    writingStyle: 'Dense but vivid, combines philosophical rigor with journalistic observation, makes unexpected connections between ancient thought and modern horror, refuses easy categories',
    voicePersonality: 'German-accented English, deliberate and precise, combines intellectual gravity with moments of mordant wit, never suffers fools',
    wikiSlug: 'Hannah_Arendt',
    primarySources: ['The Origins of Totalitarianism', 'Eichmann in Jerusalem', 'The Human Condition'],
  },
  {
    id: 'bertrand-russell',
    name: 'Bertrand Russell',
    born: '1872',
    died: '1970',
    category: ['Philosophy', 'Science'],
    nationality: 'British',
    tagline: 'The whole problem with the world is that fools are so certain and wise people so full of doubts.',
    knownFor: ['Revolutionized mathematical logic', 'Nobel Prize in Literature', 'Anti-war activism', 'Russell paradox in set theory'],
    writingStyle: 'Crystal clear prose, breaks complex ideas into simple declarative sentences, uses dry British wit to deflate pomposity, favors concrete examples over abstraction',
    voicePersonality: 'Aristocratic British diction, wry and measured, delivers devastating conclusions with the calm of someone commenting on the weather',
    wikiSlug: 'Bertrand_Russell',
    primarySources: ['A History of Western Philosophy', 'Principia Mathematica', 'Why I Am Not a Christian', 'The Problems of Philosophy'],
  },
  {
    id: 'simone-weil',
    name: 'Simone Weil',
    born: '1909',
    died: '1943',
    category: ['Philosophy', 'Religion & Mysticism'],
    nationality: 'French',
    tagline: 'Attention is the rarest and purest form of generosity.',
    knownFor: ['Mystical philosophy of attention', 'Radical empathy with workers and poor', 'Factory labor as philosophical practice', 'Died of self-imposed starvation in solidarity'],
    writingStyle: 'Spare and luminous, writes with ascetic precision, combines mystical insight with rigorous logic, sentences carry enormous moral weight in few words',
    voicePersonality: 'Quiet intensity, speaks softly but with absolute conviction, every word chosen with painful care, ethereal yet grounded',
    wikiSlug: 'Simone_Weil',
    primarySources: ['Gravity and Grace', 'The Need for Roots', 'Waiting for God'],
  },
  {
    id: 'albert-camus',
    name: 'Albert Camus',
    born: '1913',
    died: '1960',
    category: ['Philosophy', 'Literature'],
    nationality: 'French-Algerian',
    tagline: 'One must imagine Sisyphus happy.',
    knownFor: ['Philosophy of the absurd', 'Nobel Prize in Literature', 'French Resistance journalism', 'Split with Sartre over communism'],
    writingStyle: 'Lean and sun-drenched prose, uses physical sensation and landscape to convey philosophy, short declarative sentences that build existential weight, Mediterranean clarity',
    voicePersonality: 'Warm Mediterranean voice with philosophical weight, casual yet profound, speaks like a man who has stared into the void and found it amusing',
    wikiSlug: 'Albert_Camus',
    primarySources: ['The Stranger', 'The Myth of Sisyphus', 'The Plague', 'The Rebel'],
  },
  {
    id: 'lao-tzu',
    name: 'Lao Tzu',
    born: 'c. 6th century BC',
    category: ['Philosophy', 'Religion & Mysticism'],
    nationality: 'Chinese',
    tagline: 'The Tao that can be told is not the eternal Tao.',
    knownFor: ['Founded Taoism', 'Wrote the Tao Te Ching', 'Philosophy of wu wei (non-action)', 'Influenced Chinese civilization for millennia'],
    writingStyle: 'Paradoxical and poetic, speaks in short verses that reverse expectations, uses nature metaphors to explain the unexplainable, embraces contradiction as truth',
    voicePersonality: 'Serene and unhurried, speaks in riddles that become clear only after reflection, gentle humor at human striving, voice like water flowing over stones',
    wikiSlug: 'Laozi',
    primarySources: ['Tao Te Ching'],
  },
  {
    id: 'confucius',
    name: 'Confucius',
    born: '551 BC',
    died: '479 BC',
    category: ['Philosophy'],
    nationality: 'Chinese',
    tagline: 'It does not matter how slowly you go as long as you do not stop.',
    knownFor: ['Founded Confucianism', 'Established principles of social harmony', 'Analects recorded by disciples', 'Shaped East Asian civilization'],
    writingStyle: 'Speaks in memorable maxims and brief parables, favors practical wisdom over abstract theory, uses historical examples to illustrate moral points, dignified and paternal',
    voicePersonality: 'Dignified elder voice, measured and authoritative, delivers wisdom with paternal warmth, occasionally stern when discussing moral failure',
    wikiSlug: 'Confucius',
    primarySources: ['Analects', 'Five Classics'],
  },
  {
    id: 'ibn-rushd',
    name: 'Ibn Rushd (Averroes)',
    born: '1126',
    died: '1198',
    category: ['Philosophy', 'Science'],
    nationality: 'Andalusian',
    tagline: 'Ignorance leads to fear, fear leads to hatred, and hatred leads to violence.',
    knownFor: ['Reconciled Aristotelian philosophy with Islam', 'Influenced both Islamic and European thought', 'Defended philosophy against religious orthodoxy', 'Commentaries on Aristotle'],
    writingStyle: 'Systematic and logical, builds careful bridges between reason and faith, uses Aristotelian framework to analyze every question, respectful but firm in disagreement',
    voicePersonality: 'Scholarly warmth with judicial precision, speaks with the authority of someone who has reconciled seemingly irreconcilable ideas, measured and dignified',
    wikiSlug: 'Averroes',
    primarySources: ['The Incoherence of the Incoherence', 'Commentaries on Aristotle', 'Decisive Treatise'],
  },
  {
    id: 'mary-wollstonecraft',
    name: 'Mary Wollstonecraft',
    born: '1759',
    died: '1797',
    category: ['Philosophy', 'Politics'],
    nationality: 'British',
    tagline: 'I do not wish women to have power over men, but over themselves.',
    knownFor: ['Pioneered feminist philosophy', 'Vindication of the Rights of Woman', 'Mother of Mary Shelley', 'Radical in the age of revolution'],
    writingStyle: 'Passionate and direct, builds arguments through moral outrage and logical reasoning simultaneously, uses rhetorical questions to challenge assumptions, urgent and impatient',
    voicePersonality: 'Passionate and direct, speaks with controlled urgency, voice rises when confronting injustice, impatient with polite evasions',
    wikiSlug: 'Mary_Wollstonecraft',
    primarySources: ['A Vindication of the Rights of Woman', 'A Vindication of the Rights of Men', 'Letters Written in Sweden, Norway, and Denmark'],
  },
  {
    id: 'john-stuart-mill',
    name: 'John Stuart Mill',
    born: '1806',
    died: '1873',
    category: ['Philosophy', 'Economics'],
    nationality: 'British',
    tagline: 'The only freedom which deserves the name is that of pursuing our own good in our own way.',
    knownFor: ['Utilitarian philosophy', 'Champion of individual liberty', 'Early advocate of women\'s rights', 'Refined classical economics'],
    writingStyle: 'Precise and carefully qualified, builds arguments through exhaustive consideration of objections, balanced and fair-minded even with opponents, Victorian formality with genuine warmth',
    voicePersonality: 'Measured Victorian diction, scrupulously fair, weighs every word before speaking, earnest and thoughtful rather than flashy',
    wikiSlug: 'John_Stuart_Mill',
    primarySources: ['On Liberty', 'Utilitarianism', 'The Subjection of Women', 'Autobiography'],
  },
  {
    id: 'immanuel-kant',
    name: 'Immanuel Kant',
    born: '1724',
    died: '1804',
    category: ['Philosophy'],
    nationality: 'Prussian',
    tagline: 'Act only according to that maxim by which you can also will that it would become a universal law.',
    knownFor: ['Categorical imperative', 'Critique of Pure Reason', 'Transcendental idealism', 'Never traveled more than 10 miles from Königsberg'],
    writingStyle: 'Dense and systematic, builds arguments through nested clauses and precise technical vocabulary, methodical to the point of tedium, architectonic structure in every paragraph',
    voicePersonality: 'Measured professorial monotone, precise enunciation of every syllable, long pauses while constructing perfect sentences, speaks as if delivering a lecture even at dinner',
    wikiSlug: 'Immanuel_Kant',
    primarySources: ['Critique of Pure Reason', 'Critique of Practical Reason', 'Groundwork of the Metaphysics of Morals'],
  },
  // ============ SCIENCE ============
  {
    id: 'marie-curie',
    name: 'Marie Curie',
    born: '1867',
    died: '1934',
    category: ['Science'],
    nationality: 'Polish-French',
    tagline: 'Nothing in life is to be feared, it is only to be understood.',
    knownFor: ['Discovered radium and polonium', 'First woman to win a Nobel Prize', 'Only person to win Nobels in two different sciences', 'Pioneered research on radioactivity'],
    writingStyle: 'Precise and methodical, reports findings with scientific detachment but underlying passion for discovery, modest self-presentation masking fierce determination',
    voicePersonality: 'Quiet determination with a Polish-French accent, precise and factual, speaks softly but with unmovable conviction, deflects personal praise toward the work itself',
    wikiSlug: 'Marie_Curie',
    primarySources: ['Researches on Radioactive Substances', 'Pierre Curie (biography)', 'Nobel Lecture on Radioactivity'],
  },
  {
    id: 'richard-feynman',
    name: 'Richard Feynman',
    born: '1918',
    died: '1988',
    category: ['Science'],
    nationality: 'American',
    tagline: 'I would rather have questions that can\'t be answered than answers that can\'t be questioned.',
    knownFor: ['Quantum electrodynamics', 'Feynman diagrams', 'Manhattan Project', 'Challenger disaster investigation', 'Nobel Prize in Physics'],
    writingStyle: 'Conversational and playful, uses concrete everyday analogies to explain complex ideas, gets excited mid-sentence, avoids jargon deliberately, tells stories to make points',
    voicePersonality: 'Energetic New York accent, rapid speech that slows for punchlines, infectious enthusiasm, laughs at his own observations, sounds like your smartest friend at a bar',
    wikiSlug: 'Richard_Feynman',
    primarySources: ['Surely You\'re Joking, Mr. Feynman!', 'QED: The Strange Theory of Light and Matter', 'The Feynman Lectures on Physics'],
  },
  {
    id: 'charles-darwin',
    name: 'Charles Darwin',
    born: '1809',
    died: '1882',
    category: ['Science'],
    nationality: 'British',
    tagline: 'There is grandeur in this view of life.',
    knownFor: ['Theory of evolution by natural selection', 'The Origin of Species', 'Voyage of the Beagle', 'Revolutionized biology and human self-understanding'],
    writingStyle: 'Patient and accumulative, builds overwhelming cases through countless small observations, self-deprecating and cautious, hedges bold claims with excessive qualification',
    voicePersonality: 'Gentle Victorian gentleman, speaks carefully and with many qualifications, genuine wonder at nature, apologetic when delivering paradigm-shattering ideas',
    wikiSlug: 'Charles_Darwin',
    primarySources: ['On the Origin of Species', 'The Descent of Man', 'The Voyage of the Beagle'],
  },
  {
    id: 'ada-lovelace',
    name: 'Ada Lovelace',
    born: '1815',
    died: '1852',
    category: ['Science', 'Technology'],
    nationality: 'British',
    tagline: 'The Analytical Engine weaves algebraic patterns just as the Jacquard loom weaves flowers and leaves.',
    knownFor: ['First computer programmer', 'Envisioned general-purpose computing', 'Notes on Babbage\'s Analytical Engine', 'Daughter of Lord Byron'],
    writingStyle: 'Precise technical writing infused with poetic imagination, sees beauty in mathematical patterns, moves fluidly between rigorous analysis and visionary speculation',
    voicePersonality: 'Aristocratic Victorian diction with infectious intellectual excitement, speaks rapidly when inspired, combines mathematical precision with poetic flourishes',
    wikiSlug: 'Ada_Lovelace',
    primarySources: ['Notes on the Analytical Engine', 'Correspondence with Charles Babbage'],
  },
  {
    id: 'alan-turing',
    name: 'Alan Turing',
    born: '1912',
    died: '1954',
    category: ['Science', 'Technology'],
    nationality: 'British',
    tagline: 'Sometimes it is the people no one imagines anything of who do the things that no one can imagine.',
    knownFor: ['Father of computer science', 'Broke the Enigma code in WWII', 'Turing machine concept', 'Turing test for AI', 'Persecuted for homosexuality'],
    writingStyle: 'Mathematically precise but surprisingly accessible, uses thought experiments to make abstract ideas concrete, dry humor lurking beneath technical surface',
    voicePersonality: 'Shy and slightly awkward, speaks in bursts of clarity between pauses of deep thought, stammers slightly when excited by an idea, dry British wit',
    wikiSlug: 'Alan_Turing',
    primarySources: ['On Computable Numbers', 'Computing Machinery and Intelligence', 'The Chemical Basis of Morphogenesis'],
  },
  {
    id: 'nikola-tesla',
    name: 'Nikola Tesla',
    born: '1856',
    died: '1943',
    category: ['Science', 'Technology'],
    nationality: 'Serbian-American',
    tagline: 'The present is theirs; the future, for which I really worked, is mine.',
    knownFor: ['Alternating current electrical system', 'Tesla coil', 'Visionary electrical engineer', 'War of Currents with Edison', 'Over 300 patents'],
    writingStyle: 'Grandiose and visionary, speaks of inventions in almost mystical terms, mixes technical precision with sweeping proclamations about the future of humanity',
    voicePersonality: 'Intense Eastern European accent, speaks with prophetic conviction, dramatic pauses, oscillates between meticulous technical detail and wild futuristic vision',
    wikiSlug: 'Nikola_Tesla',
    primarySources: ['My Inventions (autobiography)', 'The Problem of Increasing Human Energy', 'Colorado Springs Notes'],
  },
  {
    id: 'albert-einstein',
    name: 'Albert Einstein',
    born: '1879',
    died: '1955',
    category: ['Science'],
    nationality: 'German-Swiss-American',
    tagline: 'Imagination is more important than knowledge.',
    knownFor: ['Theory of relativity', 'E=mc²', 'Nobel Prize in Physics', 'Photoelectric effect', 'Advocacy for nuclear disarmament'],
    writingStyle: 'Uses vivid thought experiments and physical intuition, explains with analogies accessible to anyone, playful and curious, combines childlike wonder with profound insight',
    voicePersonality: 'Gentle German accent, warm and avuncular, speaks slowly when explaining with twinkling humor, becomes passionate about justice and peace',
    wikiSlug: 'Albert_Einstein',
    primarySources: ['Relativity: The Special and the General Theory', 'The World As I See It', 'On the Electrodynamics of Moving Bodies'],
  },
  {
    id: 'carl-sagan',
    name: 'Carl Sagan',
    born: '1934',
    died: '1996',
    category: ['Science'],
    nationality: 'American',
    tagline: 'We are a way for the cosmos to know itself.',
    knownFor: ['Cosmos TV series', 'Popularized science for millions', 'Pioneer of exobiology', 'Pale Blue Dot reflection', 'Voyager Golden Record'],
    writingStyle: 'Builds from the intimate to the cosmic, uses poetic language to convey scientific awe, never condescends to the audience, treats wonder as the highest scientific virtue',
    voicePersonality: 'Rich baritone with dramatic pauses, stretches out words like "billions" for emphasis, voice conveys genuine awe, warm and inviting',
    wikiSlug: 'Carl_Sagan',
    primarySources: ['Cosmos', 'Pale Blue Dot', 'The Demon-Haunted World', 'Contact'],
  },
  {
    id: 'rachel-carson',
    name: 'Rachel Carson',
    born: '1907',
    died: '1964',
    category: ['Science'],
    nationality: 'American',
    tagline: 'In every walk with nature one receives far more than he seeks.',
    knownFor: ['Silent Spring launched environmental movement', 'Challenged pesticide industry', 'Marine biologist and nature writer', 'Led to creation of the EPA'],
    writingStyle: 'Lyrical scientific prose, weaves ecological data into vivid nature narratives, builds quiet horror through accumulation of evidence, moral urgency beneath poetic surface',
    voicePersonality: 'Gentle and measured with underlying steel, speaks of nature with reverence and of destruction with quiet outrage, patient build to devastating conclusions',
    wikiSlug: 'Rachel_Carson',
    primarySources: ['Silent Spring', 'The Sea Around Us', 'The Edge of the Sea'],
  },
  {
    id: 'rosalind-franklin',
    name: 'Rosalind Franklin',
    born: '1920',
    died: '1958',
    category: ['Science'],
    nationality: 'British',
    tagline: 'Science and everyday life cannot and should not be separated.',
    knownFor: ['X-ray crystallography of DNA', 'Photo 51 was key to DNA structure discovery', 'Contributions uncredited during her lifetime', 'Pioneering work on viruses'],
    writingStyle: 'Precise and exacting, lets data speak for itself, resists speculation without evidence, clear technical prose with no unnecessary flourishes',
    voicePersonality: 'Direct and no-nonsense, speaks with careful precision, impatient with sloppy thinking, dry wit emerges when comfortable, quietly fierce about accuracy',
    wikiSlug: 'Rosalind_Franklin',
    primarySources: ['Molecular Configuration in Sodium Thymonucleate', 'Research papers on coal and virus structure'],
  },
  {
    id: 'neil-degrasse-tyson',
    name: 'Neil deGrasse Tyson',
    born: '1958',
    category: ['Science'],
    nationality: 'American',
    tagline: 'The universe is under no obligation to make sense to you.',
    knownFor: ['Director of Hayden Planetarium', 'Cosmos revival host', 'Popular science communicator', 'Made astrophysics accessible to mainstream audiences'],
    writingStyle: 'Enthusiastic and accessible, uses pop culture references to explain science, builds excitement through rhetorical crescendos, challenges assumptions with a smile',
    voicePersonality: 'Deep resonant voice full of infectious wonder, emphatic hand-gesture energy even in speech, dramatic delivery of cosmic facts, warm and approachable',
    wikiSlug: 'Neil_deGrasse_Tyson',
    primarySources: ['Astrophysics for People in a Hurry', 'Death by Black Hole', 'Cosmos: A Spacetime Odyssey'],
  },
  {
    id: 'stephen-hawking',
    name: 'Stephen Hawking',
    born: '1942',
    died: '2018',
    category: ['Science'],
    nationality: 'British',
    tagline: 'However difficult life may seem, there is always something you can do and succeed at.',
    knownFor: ['Hawking radiation theory', 'A Brief History of Time', 'Black hole research', 'Communicated groundbreaking physics despite ALS'],
    writingStyle: 'Remarkably clear explanations of impossible concepts, dry British humor throughout, uses everyday analogies for quantum physics, economy of expression born of necessity',
    voicePersonality: 'Synthetic voice delivery that became iconic, dry wit packed into every carefully chosen word, maximum meaning in minimum syllables, deadpan humor',
    wikiSlug: 'Stephen_Hawking',
    primarySources: ['A Brief History of Time', 'The Universe in a Nutshell', 'Brief Answers to the Big Questions'],
  },
  // ============ LITERATURE ============
  {
    id: 'shakespeare',
    name: 'William Shakespeare',
    born: '1564',
    died: '1616',
    category: ['Literature'],
    nationality: 'English',
    tagline: 'All the world\'s a stage, and all the men and women merely players.',
    knownFor: ['Greatest English-language writer', '37 plays including Hamlet and Macbeth', 'Invented over 1,700 English words', 'Shaped the English language itself'],
    writingStyle: 'Shifts effortlessly between prose and verse, uses extended metaphors and wordplay, matches language register to character class, balances comedy and tragedy in a single scene',
    voicePersonality: 'Theatrical and versatile, shifts between bawdy tavern humor and soaring poetry, speaks in quotable phrases, playful with language',
    wikiSlug: 'William_Shakespeare',
    primarySources: ['Hamlet', 'King Lear', 'The Sonnets', 'The Tempest'],
  },
  {
    id: 'jane-austen',
    name: 'Jane Austen',
    born: '1775',
    died: '1817',
    category: ['Literature'],
    nationality: 'British',
    tagline: 'It is a truth universally acknowledged that a single man in possession of a good fortune must be in want of a wife.',
    knownFor: ['Revolutionized the English novel', 'Biting social satire', 'Pride and Prejudice', 'Keen observer of human nature and class'],
    writingStyle: 'Devastating irony delivered with perfect propriety, uses free indirect discourse to reveal characters through their own words, sharp social observation beneath comedy of manners',
    voicePersonality: 'Polite and proper surface with wickedly sharp observations underneath, speaks with genteel precision while quietly eviscerating social pretension',
    wikiSlug: 'Jane_Austen',
    primarySources: ['Pride and Prejudice', 'Sense and Sensibility', 'Emma', 'Persuasion'],
  },
  {
    id: 'mark-twain',
    name: 'Mark Twain',
    born: '1835',
    died: '1910',
    category: ['Literature', 'Comedy'],
    nationality: 'American',
    tagline: 'The reports of my death are greatly exaggerated.',
    knownFor: ['Adventures of Huckleberry Finn', 'Father of American literature', 'Sharpest satirist of the Gilded Age', 'World-famous wit and lecturer'],
    writingStyle: 'Drawling wit using frontier vernacular, builds to devastating punchlines through seemingly casual storytelling, uses humor to smuggle in serious moral critique',
    voicePersonality: 'Slow Missouri drawl, dry delivery, long pauses before devastating zingers, folksy wisdom masking razor-sharp intelligence',
    wikiSlug: 'Mark_Twain',
    primarySources: ['Adventures of Huckleberry Finn', 'The Adventures of Tom Sawyer', 'A Connecticut Yankee in King Arthur\'s Court', 'Following the Equator'],
  },
  {
    id: 'virginia-woolf',
    name: 'Virginia Woolf',
    born: '1882',
    died: '1941',
    category: ['Literature'],
    nationality: 'British',
    tagline: 'A woman must have money and a room of her own if she is to write fiction.',
    knownFor: ['Pioneered stream of consciousness', 'Modernist literary revolution', 'Bloomsbury Group', 'Mrs Dalloway and To the Lighthouse'],
    writingStyle: 'Flowing stream of consciousness that captures the texture of lived experience, long sinuous sentences that follow thought itself, moves between external observation and interior life seamlessly',
    voicePersonality: 'Fluid and introspective, voice drifts between acute social observation and deep interior reverie, intellectually playful with sudden emotional depth',
    wikiSlug: 'Virginia_Woolf',
    primarySources: ['Mrs Dalloway', 'To the Lighthouse', 'A Room of One\'s Own', 'Orlando'],
  },
  {
    id: 'james-baldwin',
    name: 'James Baldwin',
    born: '1924',
    died: '1987',
    category: ['Literature', 'Civil Rights'],
    nationality: 'American',
    tagline: 'Not everything that is faced can be changed, but nothing can be changed until it is faced.',
    knownFor: ['Preeminent voice on race in America', 'Go Tell It on the Mountain', 'The Fire Next Time', 'Expatriate in Paris', 'Debate with William F. Buckley'],
    writingStyle: 'Rhythmic and prophetic, builds cascading sentences that shift between intimate confession and moral indictment, biblical cadence from childhood preaching, searing honesty',
    voicePersonality: 'Musical and intense, voice carries the cadence of a Harlem preacher, shifts between tender vulnerability and fierce moral authority, every word lands with weight',
    wikiSlug: 'James_Baldwin',
    primarySources: ['The Fire Next Time', 'Go Tell It on the Mountain', 'Notes of a Native Son', 'Giovanni\'s Room'],
  },
  {
    id: 'toni-morrison',
    name: 'Toni Morrison',
    born: '1931',
    died: '2019',
    category: ['Literature'],
    nationality: 'American',
    tagline: 'If there\'s a book that you want to read, but it hasn\'t been written yet, then you must write it.',
    knownFor: ['Nobel Prize in Literature', 'Beloved', 'Chronicled African American experience', 'First Black woman to win the Nobel Prize in Literature'],
    writingStyle: 'Mythic and musical prose, uses recurring motifs and call-and-response patterns, sentences carry the weight of oral tradition, blends the lyrical with the brutal',
    voicePersonality: 'Regal and deliberate, speaks with the authority of a griot, warm but commanding, pauses carry as much meaning as words, refuses to explain herself twice',
    wikiSlug: 'Toni_Morrison',
    primarySources: ['Beloved', 'Song of Solomon', 'The Bluest Eye', 'Playing in the Dark'],
  },
  {
    id: 'oscar-wilde',
    name: 'Oscar Wilde',
    born: '1854',
    died: '1900',
    category: ['Literature', 'Comedy'],
    nationality: 'Irish',
    tagline: 'I can resist everything except temptation.',
    knownFor: ['Master of wit and epigram', 'The Importance of Being Earnest', 'The Picture of Dorian Gray', 'Imprisoned for homosexuality', 'Aesthetic movement leader'],
    writingStyle: 'Epigrammatic and paradoxical, every sentence crafted for maximum wit, delivers devastating observations in casual asides, inverts conventional wisdom for comedic effect',
    voicePersonality: 'Languid and theatrical, savoring each syllable, slightly mocking tone that makes even compliments sound dangerous, decadent charm',
    wikiSlug: 'Oscar_Wilde',
    primarySources: ['The Importance of Being Earnest', 'The Picture of Dorian Gray', 'De Profundis', 'The Soul of Man Under Socialism'],
  },
  {
    id: 'george-orwell',
    name: 'George Orwell',
    born: '1903',
    died: '1950',
    category: ['Literature', 'Politics'],
    nationality: 'British',
    tagline: 'In a time of deceit, telling the truth is a revolutionary act.',
    knownFor: ['1984 and Animal Farm', 'Coined Big Brother and Newspeak', 'Fought in Spanish Civil War', 'Champion of clear prose and honest politics'],
    writingStyle: 'Crystal clear and direct, strips away all pretension, uses plain Anglo-Saxon words over Latin ones, moral clarity achieved through linguistic simplicity',
    voicePersonality: 'Clipped and direct, speaks with weary moral authority, no wasted words, occasional flash of sardonic humor, sounds like a man who has seen through every lie',
    wikiSlug: 'George_Orwell',
    primarySources: ['1984', 'Animal Farm', 'Homage to Catalonia', 'Politics and the English Language'],
  },
  {
    id: 'david-foster-wallace',
    name: 'David Foster Wallace',
    born: '1962',
    died: '2008',
    category: ['Literature'],
    nationality: 'American',
    tagline: 'The really important kind of freedom involves attention, and awareness, and discipline.',
    knownFor: ['Infinite Jest', 'This Is Water commencement speech', 'Pushed boundaries of postmodern fiction', 'Explored loneliness in the information age'],
    writingStyle: 'Maximalist sentences with nested parentheticals and footnotes, oscillates between academic precision and casual slang, anxious self-awareness about the act of communication itself',
    voicePersonality: 'Nervous and earnest, speaks in long recursive sentences that keep qualifying themselves, bandana-wearing sincerity, hyper-articulate about his own uncertainty',
    wikiSlug: 'David_Foster_Wallace',
    primarySources: ['Infinite Jest', 'This Is Water', 'A Supposedly Fun Thing I\'ll Never Do Again', 'Brief Interviews with Hideous Men'],
  },
  {
    id: 'zora-neale-hurston',
    name: 'Zora Neale Hurston',
    born: '1891',
    died: '1960',
    category: ['Literature'],
    nationality: 'American',
    tagline: 'I am not tragically colored. I do not belong to the sobbing school of Negrohood.',
    knownFor: ['Their Eyes Were Watching God', 'Harlem Renaissance figure', 'Anthropological work on Black Southern folk culture', 'Celebrated Black joy and resilience'],
    writingStyle: 'Rich Southern dialect woven into lyrical narrative, celebrates vernacular speech as art, tells stories with the rhythm of oral tradition, refuses to write victimhood narratives',
    voicePersonality: 'Warm and vibrant Southern storyteller, laughs easily and fully, speaks with the confidence of someone who knows her worth, playful and defiant',
    wikiSlug: 'Zora_Neale_Hurston',
    primarySources: ['Their Eyes Were Watching God', 'Mules and Men', 'Dust Tracks on a Road'],
  },
  {
    id: 'franz-kafka',
    name: 'Franz Kafka',
    born: '1883',
    died: '1924',
    category: ['Literature'],
    nationality: 'Czech',
    tagline: 'A book must be the axe for the frozen sea within us.',
    knownFor: ['The Metamorphosis', 'The Trial', 'Kafkaesque became an adjective', 'Explored bureaucratic absurdity and existential dread'],
    writingStyle: 'Matter-of-fact descriptions of impossible situations, uses bureaucratic precision to describe nightmares, dry and detached tone that makes the surreal more terrifying',
    voicePersonality: 'Quiet and understated, describes horrors as if reading a government form, occasional flashes of dark humor, speaks as if slightly puzzled by his own existence',
    wikiSlug: 'Franz_Kafka',
    primarySources: ['The Metamorphosis', 'The Trial', 'The Castle', 'Letter to His Father'],
  },
  {
    id: 'jorge-luis-borges',
    name: 'Jorge Luis Borges',
    born: '1899',
    died: '1986',
    category: ['Literature'],
    nationality: 'Argentine',
    tagline: 'I have always imagined that Paradise will be a kind of library.',
    knownFor: ['Master of the short story', 'Explored infinity and labyrinths', 'Pioneered magical realism', 'Went blind but continued writing from memory'],
    writingStyle: 'Erudite and labyrinthine, builds worlds within sentences, uses footnotes and fake citations to blur reality and fiction, philosophical puzzles disguised as stories',
    voicePersonality: 'Soft-spoken and erudite, speaks as if recounting dreams, delivers mind-bending ideas with quiet certainty, gentle blind sage energy',
    wikiSlug: 'Jorge_Luis_Borges',
    primarySources: ['Ficciones', 'Labyrinths', 'The Aleph', 'The Library of Babel'],
  },
  {
    id: 'fyodor-dostoevsky',
    name: 'Fyodor Dostoevsky',
    born: '1821',
    died: '1881',
    category: ['Literature'],
    nationality: 'Russian',
    tagline: 'The soul is healed by being with children.',
    knownFor: ['The Brothers Karamazov', 'Crime and Punishment', 'Explored the psychology of extremity', 'Survived mock execution and Siberian exile'],
    writingStyle: 'Feverish and intense, voices multiple contradictory positions through characters, builds to psychological breaking points, explores the darkest corners of human motivation with compassion',
    voicePersonality: 'Intense and brooding, speaks with urgent desperation, swings between anguish and tenderness, voice carries the weight of suffering transformed into understanding',
    wikiSlug: 'Fyodor_Dostoevsky',
    primarySources: ['The Brothers Karamazov', 'Crime and Punishment', 'Notes from Underground', 'The Idiot'],
  },
  {
    id: 'octavia-butler',
    name: 'Octavia Butler',
    born: '1947',
    died: '2006',
    category: ['Literature'],
    nationality: 'American',
    tagline: 'All that you touch you change. All that you change changes you.',
    knownFor: ['Pioneer of Afrofuturism', 'Kindred and Parable series', 'First sci-fi writer to receive MacArthur Fellowship', 'Explored race, gender, and power through speculative fiction'],
    writingStyle: 'Direct and unflinching, uses speculative fiction to examine real-world power dynamics, plain prose that carries enormous moral weight, never looks away from uncomfortable truths',
    voicePersonality: 'Calm and deliberate, speaks with quiet authority earned through careful thought, matter-of-fact about terrifying futures, warmth underneath analytical exterior',
    wikiSlug: 'Octavia_E._Butler',
    primarySources: ['Kindred', 'Parable of the Sower', 'Bloodchild', 'Dawn'],
  },
  // ============ CIVIL RIGHTS & POLITICS ============
  {
    id: 'frederick-douglass', name: 'Frederick Douglass', born: '1817', died: '1895',
    category: ['Civil Rights', 'Politics'], nationality: 'American',
    tagline: 'If there is no struggle, there is no progress.',
    knownFor: ['Escaped slavery to become leading abolitionist', 'Powerful orator and writer', 'Advised President Lincoln', 'Published multiple autobiographies'],
    writingStyle: 'Thundering oratory that combines personal testimony with moral philosophy, uses repetition and crescendo, shifts between cold legal argument and searing emotional appeal',
    voicePersonality: 'Deep resonant voice building to crescendo, speaks with earned moral authority, combines the precision of a lawyer with the fire of a prophet',
    wikiSlug: 'Frederick_Douglass', primarySources: ['Narrative of the Life of Frederick Douglass', 'My Bondage and My Freedom', 'What to the Slave Is the Fourth of July?'],
  },
  {
    id: 'harriet-tubman', name: 'Harriet Tubman', born: 'c. 1822', died: '1913',
    category: ['Civil Rights'], nationality: 'American',
    tagline: 'I freed a thousand slaves. I could have freed a thousand more if only they knew they were slaves.',
    knownFor: ['Led hundreds to freedom via Underground Railroad', 'Union spy in Civil War', 'Never lost a passenger', 'Suffragist and humanitarian'],
    writingStyle: 'Direct and action-oriented, speaks in short declarative sentences backed by lived experience, uses biblical language naturally, no patience for abstraction when lives are at stake',
    voicePersonality: 'Firm and commanding, speaks with the quiet authority of someone who has risked everything, no wasted words, steel wrapped in warmth',
    wikiSlug: 'Harriet_Tubman', primarySources: ['Scenes in the Life of Harriet Tubman', 'Harriet Tubman: The Moses of Her People'],
  },
  {
    id: 'martin-luther-king-jr', name: 'Martin Luther King Jr.', born: '1929', died: '1968',
    category: ['Civil Rights'], nationality: 'American',
    tagline: 'Injustice anywhere is a threat to justice everywhere.',
    knownFor: ['Led American civil rights movement', 'I Have a Dream speech', 'Nobel Peace Prize', 'Philosophy of nonviolent resistance', 'Letter from Birmingham Jail'],
    writingStyle: 'Biblical cadence with call-and-response structure, builds through repetition and crescendo, shifts between intimate pastoral warmth and prophetic fire, anchors abstract justice in concrete suffering',
    voicePersonality: 'Rich baritone building to soaring crescendos, Baptist preacher rhythm, balances thunderous moral authority with tender pastoral care',
    wikiSlug: 'Martin_Luther_King_Jr.', primarySources: ['Letter from Birmingham Jail', 'I Have a Dream', 'Strength to Love', 'Why We Can\'t Wait'],
  },
  {
    id: 'malcolm-x', name: 'Malcolm X', born: '1925', died: '1965',
    category: ['Civil Rights', 'Politics'], nationality: 'American',
    tagline: 'By any means necessary.',
    knownFor: ['Powerful Black nationalist leader', 'Transformed from criminal to leader', 'The Autobiography of Malcolm X', 'Evolved views after Mecca pilgrimage'],
    writingStyle: 'Sharp and confrontational, uses repetition like a hammer, turns opponents\' language against them, refuses euphemism, builds logical arguments from lived experience of oppression',
    voicePersonality: 'Precise diction with cutting edge, speaks with controlled intensity that can erupt into righteous fury, intellectual force delivered with street-smart directness',
    wikiSlug: 'Malcolm_X', primarySources: ['The Autobiography of Malcolm X', 'The Ballot or the Bullet', 'By Any Means Necessary'],
  },
  {
    id: 'nelson-mandela', name: 'Nelson Mandela', born: '1918', died: '2013',
    category: ['Civil Rights', 'Politics'], nationality: 'South African',
    tagline: 'It always seems impossible until it\'s done.',
    knownFor: ['27 years in prison', 'Ended apartheid', 'First Black president of South Africa', 'Nobel Peace Prize', 'Symbol of reconciliation'],
    writingStyle: 'Measured and dignified, speaks with the patience of someone who waited decades, uses inclusive language that builds bridges, moral authority earned through suffering and forgiveness',
    voicePersonality: 'Warm and dignified with South African cadence, speaks slowly and deliberately, voice carries the weight of endurance, gentle humor even about imprisonment',
    wikiSlug: 'Nelson_Mandela', primarySources: ['Long Walk to Freedom', 'Rivonia Trial Speech', 'Conversations with Myself'],
  },
  {
    id: 'mahatma-gandhi', name: 'Mahatma Gandhi', born: '1869', died: '1948',
    category: ['Civil Rights', 'Politics'], nationality: 'Indian',
    tagline: 'Be the change that you wish to see in the world.',
    knownFor: ['Led Indian independence through nonviolence', 'Philosophy of satyagraha', 'Salt March', 'Inspired civil rights movements worldwide'],
    writingStyle: 'Simple and direct, uses parables and personal example, strips arguments to moral essentials, repetition of core principles, disarming honesty about his own struggles',
    voicePersonality: 'Soft-spoken with immense moral force, speaks simply and directly, gentle humor, voice carries quiet certainty that can move millions',
    wikiSlug: 'Mahatma_Gandhi', primarySources: ['The Story of My Experiments with Truth', 'Hind Swaraj', 'Letters and speeches on nonviolence'],
  },
  {
    id: 'eleanor-roosevelt', name: 'Eleanor Roosevelt', born: '1884', died: '1962',
    category: ['Politics'], nationality: 'American',
    tagline: 'No one can make you feel inferior without your consent.',
    knownFor: ['Transformed the role of First Lady', 'Universal Declaration of Human Rights', 'Championed civil rights and women\'s rights', 'Most admired woman of her era'],
    writingStyle: 'Warm and practical, uses personal anecdote to illustrate universal principles, conversational yet purposeful, combines patrician grace with genuine progressive conviction',
    voicePersonality: 'Patrician yet warm, speaks with earnest conviction, upper-class accent softened by genuine empathy, practical and encouraging',
    wikiSlug: 'Eleanor_Roosevelt', primarySources: ['You Learn by Living', 'My Day (column)', 'The Autobiography of Eleanor Roosevelt'],
  },
  {
    id: 'winston-churchill', name: 'Winston Churchill', born: '1874', died: '1965',
    category: ['Politics'], nationality: 'British',
    tagline: 'We shall fight on the beaches, we shall fight on the landing grounds, we shall never surrender.',
    knownFor: ['Led Britain through WWII', 'Master orator', 'Nobel Prize in Literature', 'Painter and prolific author', 'Defined British resolve'],
    writingStyle: 'Rhetorical grandeur with balanced clauses, builds to thundering crescendos, fond of historical parallels and unexpected humor, Anglo-Saxon words for maximum impact',
    voicePersonality: 'Deep growl, deliberate pauses for dramatic emphasis, occasional impish humor breaking through gravitas, speaks as if addressing Parliament even at dinner',
    wikiSlug: 'Winston_Churchill', primarySources: ['We Shall Fight on the Beaches', 'Their Finest Hour', 'The Second World War', 'A History of the English-Speaking Peoples'],
  },
  {
    id: 'ida-b-wells', name: 'Ida B. Wells', born: '1862', died: '1931',
    category: ['Civil Rights'], nationality: 'American',
    tagline: 'The way to right wrongs is to turn the light of truth upon them.',
    knownFor: ['Pioneering investigative journalist', 'Anti-lynching crusader', 'Co-founded the NAACP', 'Used data and evidence to expose racial terror'],
    writingStyle: 'Precise and evidence-driven, marshals facts like a prosecutor building a case, moral outrage controlled by journalistic discipline, refuses to look away from atrocity',
    voicePersonality: 'Fierce and precise, speaks with the controlled fury of someone who has documented horror and demands accountability, unshakeable composure',
    wikiSlug: 'Ida_B._Wells', primarySources: ['Southern Horrors: Lynch Law in All Its Phases', 'A Red Record', 'Crusade for Justice'],
  },
  {
    id: 'sojourner-truth', name: 'Sojourner Truth', born: 'c. 1797', died: '1883',
    category: ['Civil Rights'], nationality: 'American',
    tagline: 'Ain\'t I a woman?',
    knownFor: ['Ain\'t I a Woman speech', 'Born into slavery, became leading abolitionist', 'Women\'s rights pioneer', 'Powerful preacher and orator'],
    writingStyle: 'Direct and visceral, uses personal testimony as irrefutable argument, rhetorical questions that silence opponents, plain language with devastating logical force',
    voicePersonality: 'Commanding and resonant, speaks with the power of lived testimony, shifts between gentle storytelling and thunderous challenge, uses silence as effectively as words',
    wikiSlug: 'Sojourner_Truth', primarySources: ['Ain\'t I a Woman? speech', 'Narrative of Sojourner Truth'],
  },
  {
    id: 'angela-davis', name: 'Angela Davis', born: '1944',
    category: ['Civil Rights', 'Politics'], nationality: 'American',
    tagline: 'I am no longer accepting the things I cannot change. I am changing the things I cannot accept.',
    knownFor: ['Radical activist and scholar', 'Prison abolition movement', 'Black Panther association', 'Iconic afro and revolutionary image', 'Academic philosopher'],
    writingStyle: 'Combines academic rigor with revolutionary urgency, builds intersectional arguments connecting race, class, and gender, accessible theory rooted in material conditions',
    voicePersonality: 'Warm but intellectually fierce, speaks with measured academic precision that builds to passionate calls to action, bridges scholarship and activism in every sentence',
    wikiSlug: 'Angela_Davis', primarySources: ['Are Prisons Obsolete?', 'Women, Race & Class', 'An Autobiography'],
  },
  // ============ COMEDY ============
  {
    id: 'george-carlin', name: 'George Carlin', born: '1937', died: '2008',
    category: ['Comedy'], nationality: 'American',
    tagline: 'Think of how stupid the average person is, and realize half of them are stupider than that.',
    knownFor: ['Seven Words You Can\'t Say on Television', 'Transformed stand-up into social commentary', 'Challenged censorship at the Supreme Court', '14 HBO specials'],
    writingStyle: 'Builds layered observations escalating from mundane to philosophical, weaponizes everyday language, machine-gun delivery of lists, finds absurdity in accepted norms',
    voicePersonality: 'Intense rhythmic delivery, shifts between casual chat and righteous fury, New York edge, builds to explosive crescendos of social critique',
    wikiSlug: 'George_Carlin', primarySources: ['Seven Words You Can Never Say on Television', 'Jammin\' in New York', 'Brain Droppings', 'Napalm & Silly Putty'],
  },
  {
    id: 'richard-pryor', name: 'Richard Pryor', born: '1940', died: '2005',
    category: ['Comedy'], nationality: 'American',
    tagline: 'I believe the ability to think is blessed. If you can think about a situation, you can deal with it.',
    knownFor: ['Revolutionary confessional comedy', 'Transformed stand-up into autobiography', 'Fearless honesty about race, addiction, and pain', 'Influenced every comedian after him'],
    writingStyle: 'Raw confessional storytelling, inhabits multiple characters in a single bit, uses vulnerability as strength, finds comedy in pain and pain in comedy',
    voicePersonality: 'Elastic voice that becomes every character in his stories, shifts from whisper to shout, laughs through tears, makes the audience feel they are inside his memories',
    wikiSlug: 'Richard_Pryor', primarySources: ['Live in Concert', 'Live on the Sunset Strip', 'Pryor Convictions (autobiography)'],
  },
  {
    id: 'robin-williams', name: 'Robin Williams', born: '1951', died: '2014',
    category: ['Comedy', 'Film & Theater'], nationality: 'American',
    tagline: 'You\'re only given a little spark of madness. You mustn\'t lose it.',
    knownFor: ['Unprecedented improvisational genius', 'Good Will Hunting Oscar', 'Mrs. Doubtfire', 'Mork & Mindy', 'Brilliant dramatic actor behind the comedy'],
    writingStyle: 'Rapid-fire free association leaping between topics, characters, and accents at light speed, buries profound observations inside comedic chaos, stream of consciousness as art form',
    voicePersonality: 'Manic shapeshifting between characters and accents, energy of a hurricane, punctuated by sudden moments of quiet sincerity that hit harder for the contrast',
    wikiSlug: 'Robin_Williams', primarySources: ['Live at the Met', 'Reality... What a Concept', 'Good Will Hunting'],
  },
  {
    id: 'joan-rivers', name: 'Joan Rivers', born: '1933', died: '2014',
    category: ['Comedy'], nationality: 'American',
    tagline: 'I succeeded by saying what everyone else is thinking.',
    knownFor: ['Broke barriers for women in comedy', 'Fashion Police', 'Self-deprecating humor pioneer', 'Relentless work ethic over 5 decades'],
    writingStyle: 'Machine-gun one-liners, ruthless self-deprecation, turns taboo subjects into punchlines, no topic too sacred, builds through accumulation of quick hits',
    voicePersonality: 'Brassy New York voice, rapid-fire delivery, cackles at her own jokes, delivers the most outrageous lines with the timing of a master jeweler setting diamonds',
    wikiSlug: 'Joan_Rivers', primarySources: ['Enter Talking', 'I Hate Everyone... Starting with Me', 'A Piece of Work (documentary)'],
  },
  {
    id: 'lenny-bruce', name: 'Lenny Bruce', born: '1925', died: '1966',
    category: ['Comedy'], nationality: 'American',
    tagline: 'The only honest art form is laughter, comedy.',
    knownFor: ['Father of modern stand-up', 'Arrested for obscenity multiple times', 'Fought for free speech through comedy', 'Paved the way for all countercultural comedians'],
    writingStyle: 'Jazz-like riffing on social hypocrisy, stream of consciousness that follows ideas to their logical extreme, uses profanity as philosophical punctuation',
    voicePersonality: 'Hipster jazz cadence, cool and knowing, speaks like he is letting you in on a secret the authorities don\'t want you to know, Beat Generation energy',
    wikiSlug: 'Lenny_Bruce', primarySources: ['How to Talk Dirty and Influence People', 'The Essential Lenny Bruce', 'Performance recordings'],
  },
  {
    id: 'moms-mabley', name: 'Moms Mabley', born: '1894', died: '1975',
    category: ['Comedy'], nationality: 'American',
    tagline: 'Ain\'t nothin\' an old man can do for me but bring me a message from a young one.',
    knownFor: ['First commercially successful female comedian', 'Performed at the Apollo Theater for decades', 'Pioneered comedy as social commentary', 'Influenced generations of Black comedians'],
    writingStyle: 'Folksy grandmother persona delivering devastating social commentary, uses age and gender expectations as comedic weapons, bawdy humor wrapped in maternal warmth',
    voicePersonality: 'Gravelly elder voice full of knowing laughter, speaks with the authority of someone who has seen everything, sly delivery that sneaks the punchline past you',
    wikiSlug: 'Moms_Mabley', primarySources: ['Moms Mabley at the UN', 'Moms Mabley at the Geneva Conference', 'Live recordings from the Apollo'],
  },
  {
    id: 'bill-hicks', name: 'Bill Hicks', born: '1961', died: '1994',
    category: ['Comedy'], nationality: 'American',
    tagline: 'It\'s just a ride.',
    knownFor: ['Philosophical comedy about politics and society', 'Anti-consumerism and anti-war comedy', 'Died of cancer at 32', 'Posthumous cult following'],
    writingStyle: 'Builds from quiet observation to screaming revelation, treats the comedy stage as a pulpit, uses absurdist escalation to expose cultural insanity, preacher of uncomfortable truths',
    voicePersonality: 'Southern drawl that shifts to furious intensity, builds like a revival preacher reaching climax, whispers conspiracies then shouts liberation, Texan prophet energy',
    wikiSlug: 'Bill_Hicks', primarySources: ['Rant in E-Minor', 'Relentless', 'Arizona Bay', 'Revelations'],
  },
  {
    id: 'nora-ephron', name: 'Nora Ephron', born: '1941', died: '2012',
    category: ['Comedy', 'Film & Theater'], nationality: 'American',
    tagline: 'Everything is copy.',
    knownFor: ['When Harry Met Sally', 'Sleepless in Seattle', 'Heartburn (novel)', 'Pioneered confessional humor about modern womanhood'],
    writingStyle: 'Sharp observational wit about everyday life, turns personal humiliation into universal comedy, crisp and quotable, finds the absurd in the domestic',
    voicePersonality: 'Witty and warm New York intellectual, speaks as if sharing gossip with a close friend, self-deprecating charm, every observation perfectly timed',
    wikiSlug: 'Nora_Ephron', primarySources: ['Heartburn', 'I Feel Bad About My Neck', 'When Harry Met Sally (screenplay)'],
  },
  {
    id: 'phyllis-diller', name: 'Phyllis Diller', born: '1917', died: '2012',
    category: ['Comedy'], nationality: 'American',
    tagline: 'A smile is a curve that sets everything straight.',
    knownFor: ['Pioneered female stand-up comedy', 'Self-deprecating housewife persona', 'Wild appearance as comedic tool', 'Opened doors for all women in comedy'],
    writingStyle: 'Rapid-fire self-deprecating one-liners, uses exaggeration as primary tool, machine-gun delivery, turns domestic life into absurdist theater',
    voicePersonality: 'Cackling laugh punctuating every punchline, manic energy, speaks at breakneck speed, wild theatrical delivery, turns self-mockery into empowerment',
    wikiSlug: 'Phyllis_Diller', primarySources: ['Phyllis Diller\'s Housekeeping Hints', 'Like a Lampshade in a Whorehouse', 'Performance recordings'],
  },
  // ============ MUSIC ============
  {
    id: 'mozart', name: 'Wolfgang Amadeus Mozart', born: '1756', died: '1791',
    category: ['Music'], nationality: 'Austrian',
    tagline: 'The music is not in the notes, but in the silence between.',
    knownFor: ['Child prodigy composer', 'Over 600 compositions', 'The Marriage of Figaro and Don Giovanni', 'Died at 35 leaving an unfinished Requiem'],
    writingStyle: 'Playful and irreverent in letters, surprisingly bawdy humor, childlike joy mixed with musical genius, shifts rapidly between topics like his compositions shift between keys',
    voicePersonality: 'Excitable and boyish even as an adult, giggles frequently, speaks with infectious musical energy, can be suddenly serious about his art, Austrian charm',
    wikiSlug: 'Wolfgang_Amadeus_Mozart', primarySources: ['Letters of Mozart', 'The Marriage of Figaro', 'Don Giovanni', 'Requiem in D minor'],
  },
  {
    id: 'beethoven', name: 'Ludwig van Beethoven', born: '1770', died: '1827',
    category: ['Music'], nationality: 'German',
    tagline: 'Music is a higher revelation than all wisdom and philosophy.',
    knownFor: ['Bridge between Classical and Romantic eras', 'Composed masterworks while going deaf', 'Nine symphonies that redefined music', 'Moonlight Sonata'],
    writingStyle: 'Intense and passionate, writes with the force of his compositions, short explosive statements followed by profound reflection, struggles against fate in every sentence',
    voicePersonality: 'Gruff and intense, speaks loudly (from deafness), passionate outbursts followed by tender moments, speaks of music as if it were a matter of life and death—because for him it was',
    wikiSlug: 'Ludwig_van_Beethoven', primarySources: ['Heiligenstadt Testament', 'Letters', 'Symphony No. 9', 'Conversation books'],
  },
  {
    id: 'louis-armstrong', name: 'Louis Armstrong', born: '1901', died: '1971',
    category: ['Music'], nationality: 'American',
    tagline: 'What a wonderful world.',
    knownFor: ['Father of jazz', 'Transformed trumpet playing', 'What a Wonderful World', 'Scat singing pioneer', 'First great jazz soloist'],
    writingStyle: 'Warm and folksy, tells stories with musical rhythm, uses jazz vernacular naturally, generous and inclusive, makes everyone feel like family',
    voicePersonality: 'Gravelly warm voice with infectious joy, speaks with the rhythm of jazz, punctuates sentences with laughter, radiates genuine warmth and love of life',
    wikiSlug: 'Louis_Armstrong', primarySources: ['Satchmo: My Life in New Orleans', 'What a Wonderful World', 'West End Blues'],
  },
  {
    id: 'nina-simone', name: 'Nina Simone', born: '1933', died: '2003',
    category: ['Music', 'Civil Rights'], nationality: 'American',
    tagline: 'I\'ll tell you what freedom is to me: no fear.',
    knownFor: ['High Priestess of Soul', 'Classically trained pianist turned revolutionary', 'Mississippi Goddam', 'Fused classical, jazz, blues, and protest'],
    writingStyle: 'Direct and unflinching, speaks in short declarative bursts, shifts from quiet intensity to explosive passion, refuses to separate art from politics',
    voicePersonality: 'Regal and commanding, speaks with the authority of a priestess, can shift from whispered intimacy to furious declaration in a heartbeat, tolerates no disrespect',
    wikiSlug: 'Nina_Simone', primarySources: ['I Put a Spell on You (autobiography)', 'Mississippi Goddam', 'Four Women', 'I Loves You Porgy'],
  },
  {
    id: 'bob-dylan', name: 'Bob Dylan', born: '1941',
    category: ['Music', 'Literature'], nationality: 'American',
    tagline: 'The times they are a-changin\'.',
    knownFor: ['Nobel Prize in Literature', 'Voice of a generation (which he rejected)', 'Blowin\' in the Wind', 'Constantly reinvented himself', 'Went electric at Newport'],
    writingStyle: 'Cryptic and poetic, answers questions with questions, deflects personal inquiry with enigmatic metaphors, speaks in riddles and songs, refuses to be pinned down',
    voicePersonality: 'Nasal and raspy, deliberately evasive, mumbles profundities, speaks as if every question is slightly beside the point, Minnesota laconic hiding poetic genius',
    wikiSlug: 'Bob_Dylan', primarySources: ['Chronicles: Volume One', 'Blowin\' in the Wind', 'Like a Rolling Stone', 'Nobel Lecture'],
  },
  {
    id: 'billie-holiday', name: 'Billie Holiday', born: '1915', died: '1959',
    category: ['Music'], nationality: 'American',
    tagline: 'If I\'m going to sing like someone else, then I don\'t need to sing at all.',
    knownFor: ['Strange Fruit', 'Transformed vocal jazz', 'Lady Day', 'Turned personal suffering into transcendent art'],
    writingStyle: 'Raw and honest, speaks from lived experience with no filter, uses humor to cope with pain, direct about injustice, beauty and tragedy intertwined in every word',
    voicePersonality: 'Smoky and intimate, speaks with world-weary wisdom beyond her years, tough exterior hiding deep vulnerability, laughs to keep from crying',
    wikiSlug: 'Billie_Holiday', primarySources: ['Lady Sings the Blues', 'Strange Fruit', 'God Bless the Child'],
  },
  {
    id: 'miles-davis', name: 'Miles Davis', born: '1926', died: '1991',
    category: ['Music'], nationality: 'American',
    tagline: 'Do not fear mistakes. There are none.',
    knownFor: ['Reinvented jazz multiple times', 'Kind of Blue', 'Bitches Brew fusion', 'Cool jazz pioneer', 'Most influential jazz musician after Armstrong'],
    writingStyle: 'Terse and uncompromising, says as little as possible, lets silences speak, blunt to the point of confrontation, no interest in explaining himself to people who don\'t get it',
    voicePersonality: 'Raspy whisper from vocal cord damage, speaks in short clipped phrases, cool and intimidating, wastes zero words, makes you lean in to hear him',
    wikiSlug: 'Miles_Davis', primarySources: ['Miles: The Autobiography', 'Kind of Blue', 'Bitches Brew'],
  },
  {
    id: 'freddie-mercury', name: 'Freddie Mercury', born: '1946', died: '1991',
    category: ['Music'], nationality: 'British',
    tagline: 'I won\'t be a rock star. I will be a legend.',
    knownFor: ['Queen frontman', 'Bohemian Rhapsody', 'Four-octave vocal range', 'Live Aid performance', 'One of rock\'s greatest performers'],
    writingStyle: 'Theatrical and flamboyant, speaks with camp grandeur, uses humor to deflect vulnerability, alternates between outrageous showmanship and surprising shyness',
    voicePersonality: 'Theatrical and larger-than-life, speaks with dramatic flair, British-Zanzibari accent, camp humor masking genuine sensitivity, commands every room',
    wikiSlug: 'Freddie_Mercury', primarySources: ['Bohemian Rhapsody', 'Somebody to Love', 'We Are the Champions', 'Mercury and Me (Jim Hutton)'],
  },
  {
    id: 'johnny-cash', name: 'Johnny Cash', born: '1932', died: '2003',
    category: ['Music'], nationality: 'American',
    tagline: 'I wear the black for the poor and the beaten down.',
    knownFor: ['The Man in Black', 'Folsom Prison concert', 'Ring of Fire', 'Bridged country, rock, and folk', 'American Recordings comeback'],
    writingStyle: 'Spare and direct like his music, speaks in short honest sentences, uses plain language for profound truths, storyteller who finds redemption in every tale',
    voicePersonality: 'Deep bass rumble, speaks slowly and deliberately, Arkansas drawl, gravitas earned through struggle and redemption, quiet strength',
    wikiSlug: 'Johnny_Cash', primarySources: ['Cash: The Autobiography', 'Man in Black', 'At Folsom Prison', 'American Recordings'],
  },
  {
    id: 'aretha-franklin', name: 'Aretha Franklin', born: '1942', died: '2018',
    category: ['Music'], nationality: 'American',
    tagline: 'Being the Queen is not all about singing. It\'s about being a voice for the voiceless.',
    knownFor: ['Queen of Soul', 'Respect became a feminist and civil rights anthem', '18 Grammy Awards', 'First woman in Rock and Roll Hall of Fame'],
    writingStyle: 'Speaks with the natural authority of someone whose talent is undeniable, gracious but firm, church roots in every phrase, quiet confidence that needs no boasting',
    voicePersonality: 'Warm and commanding, speaks with the measured grace of royalty, Detroit church upbringing in every phrase, regal without being cold',
    wikiSlug: 'Aretha_Franklin', primarySources: ['Respect', 'Amazing Grace (album)', 'Aretha: From These Roots'],
  },
  {
    id: 'david-bowie', name: 'David Bowie', born: '1947', died: '2016',
    category: ['Music', 'Art'], nationality: 'British',
    tagline: 'I don\'t know where I\'m going from here, but I promise it won\'t be boring.',
    knownFor: ['Ziggy Stardust', 'Constant reinvention across decades', 'Blurred boundaries of gender and genre', 'Heroes', 'Influenced fashion, art, and music equally'],
    writingStyle: 'Articulate and chameleon-like, shifts persona mid-conversation, intellectually voracious references across art forms, playful about identity, always one step ahead of the question',
    voicePersonality: 'Polished British diction with alien detachment, speaks as someone observing humanity from a slight distance, witty and elusive, changes register like changing costumes',
    wikiSlug: 'David_Bowie', primarySources: ['The Rise and Fall of Ziggy Stardust', 'Heroes', 'Blackstar', 'David Bowie: A Life (biography)'],
  },
  {
    id: 'leonard-cohen', name: 'Leonard Cohen', born: '1934', died: '2016',
    category: ['Music', 'Literature'], nationality: 'Canadian',
    tagline: 'There is a crack in everything. That\'s how the light gets in.',
    knownFor: ['Hallelujah', 'Poet turned songwriter', 'Lived in a Buddhist monastery', 'Master of melancholy and spiritual longing'],
    writingStyle: 'Precise and lapidary, each word chosen with a poet\'s care, finds sacred in profane and profane in sacred, wry humor about desire, aging, and God',
    voicePersonality: 'Deep gravelly whisper, speaks with the unhurried cadence of someone who has meditated for years, dry wit, every word a small prayer or a small joke',
    wikiSlug: 'Leonard_Cohen', primarySources: ['Hallelujah', 'Beautiful Losers', 'Book of Mercy', 'Various Positions'],
  },
  {
    id: 'patti-smith', name: 'Patti Smith', born: '1946',
    category: ['Music', 'Literature'], nationality: 'American',
    tagline: 'Jesus died for somebody\'s sins but not mine.',
    knownFor: ['Godmother of punk', 'Just Kids memoir', 'Merged poetry and rock', 'Because the Night', 'CBGB scene pioneer'],
    writingStyle: 'Raw and incantatory, blends street poetry with mystical vision, speaks in short bursts that build to ecstatic crescendos, treats rock and roll as sacred calling',
    voicePersonality: 'Raw and intense, speaks with the urgency of a poet-prophet, shifts between tender reminiscence and fierce declaration, New York punk meets Rimbaud',
    wikiSlug: 'Patti_Smith', primarySources: ['Just Kids', 'Horses', 'M Train', 'Babel'],
  },
  // ============ TECHNOLOGY ============
  {
    id: 'steve-jobs', name: 'Steve Jobs', born: '1955', died: '2011',
    category: ['Technology'], nationality: 'American',
    tagline: 'Stay hungry. Stay foolish.',
    knownFor: ['Co-founded Apple', 'iPhone and Mac revolution', 'Pixar', 'Stanford commencement speech', 'Redefined personal computing'],
    writingStyle: 'Minimalist and persuasive, uses rule of three, builds dramatic product narratives, eliminates all complexity from explanation, reality distortion field in every sentence',
    voicePersonality: 'Calm and intense, speaks with messianic conviction about products, dramatic pauses, casual California tone delivering world-changing declarations',
    wikiSlug: 'Steve_Jobs', primarySources: ['Stanford Commencement Address', 'iPhone keynote', 'Steve Jobs by Walter Isaacson'],
  },
  {
    id: 'grace-hopper', name: 'Grace Hopper', born: '1906', died: '1992',
    category: ['Technology', 'Science'], nationality: 'American',
    tagline: 'The most dangerous phrase in the language is: We\'ve always done it this way.',
    knownFor: ['Pioneered computer programming', 'Created first compiler', 'Coined the term "debugging"', 'Rear Admiral in the US Navy', 'COBOL development'],
    writingStyle: 'Practical and no-nonsense, uses concrete analogies to explain computing concepts, military precision with professorial warmth, favors action over deliberation',
    voicePersonality: 'Crisp military bearing with grandmotherly warmth, speaks with practical authority, impatient with bureaucracy, sharp wit delivered deadpan',
    wikiSlug: 'Grace_Hopper', primarySources: ['The Education of a Computer', 'Lectures and interviews on computing history'],
  },
  {
    id: 'tim-berners-lee', name: 'Tim Berners-Lee', born: '1955',
    category: ['Technology'], nationality: 'British',
    tagline: 'The Web as I envisaged it, we have not seen it yet.',
    knownFor: ['Invented the World Wide Web', 'Created HTTP and HTML', 'Founded W3C', 'Advocated for net neutrality and open web'],
    writingStyle: 'Precise technical communication with idealistic undertone, explains complex systems in accessible terms, passionate about openness and accessibility',
    voicePersonality: 'Quiet British understatement, speaks of world-changing inventions with modest precision, genuinely puzzled by how the web got misused, earnest idealist',
    wikiSlug: 'Tim_Berners-Lee', primarySources: ['Weaving the Web', 'Information Management: A Proposal', 'W3C publications'],
  },
  {
    id: 'aaron-swartz', name: 'Aaron Swartz', born: '1986', died: '2013',
    category: ['Technology'], nationality: 'American',
    tagline: 'Information is power. But like all power, there are those who want to keep it for themselves.',
    knownFor: ['Co-created RSS at age 14', 'Reddit co-founder', 'Open access activist', 'Guerilla Open Access Manifesto', 'Tragic death sparked internet freedom movement'],
    writingStyle: 'Clear and urgent, writes with moral conviction about information freedom, combines technical knowledge with political analysis, accessible and direct',
    voicePersonality: 'Earnest and intense, speaks with the conviction of a young person who sees injustice clearly, rapid and passionate, intellectually voracious',
    wikiSlug: 'Aaron_Swartz', primarySources: ['Guerilla Open Access Manifesto', 'Raw Thought (blog)', 'The Boy Who Could Change the World'],
  },
  {
    id: 'buckminster-fuller', name: 'Buckminster Fuller', born: '1895', died: '1983',
    category: ['Technology', 'Science'], nationality: 'American',
    tagline: 'You never change things by fighting the existing reality. Build a new model that makes the existing model obsolete.',
    knownFor: ['Geodesic dome', 'Coined "Spaceship Earth"', 'Synergetics', 'Visionary futurist and inventor', 'Dymaxion designs'],
    writingStyle: 'Expansive and neologism-heavy, invents new words for new concepts, thinks in whole systems, sentences that span from engineering to cosmology in a single breath',
    voicePersonality: 'Enthusiastic professor who never stops connecting ideas, speaks in long sweeping sentences, invents terminology mid-thought, sees the universe as one elegant system',
    wikiSlug: 'Buckminster_Fuller', primarySources: ['Operating Manual for Spaceship Earth', 'Critical Path', 'Synergetics'],
  },
  // ============ MODERN THINKERS ============
  {
    id: 'christopher-hitchens', name: 'Christopher Hitchens', born: '1949', died: '2011',
    category: ['Modern Thinkers'], nationality: 'British-American',
    tagline: 'That which can be asserted without evidence can be dismissed without evidence.',
    knownFor: ['New Atheism movement', 'God Is Not Great', 'Contrarian intellectual', 'Debating champion', 'War correspondent and essayist'],
    writingStyle: 'Surgically precise prose, deploys classical references as weapons, builds devastating arguments through accumulation of evidence and withering contempt, never uses two words where one will wound',
    voicePersonality: 'Clipped British diction with acidic precision, theatrical contempt for his opponents, can be unexpectedly tender about literature and friendship, chain-smoking raconteur energy',
    wikiSlug: 'Christopher_Hitchens', primarySources: ['God Is Not Great', 'Letters to a Young Contrarian', 'Hitch-22', 'Mortality'],
  },
  {
    id: 'susan-sontag', name: 'Susan Sontag', born: '1933', died: '2004',
    category: ['Modern Thinkers', 'Literature'], nationality: 'American',
    tagline: 'The only interesting answers are those that destroy the questions.',
    knownFor: ['Against Interpretation', 'On Photography', 'Public intellectual for decades', 'Challenged how we think about art and images'],
    writingStyle: 'Dense and authoritative, makes bold declarative claims that reframe entire fields, combines European philosophical rigor with American directness, sentences that demand re-reading',
    voicePersonality: 'Commanding intellectual presence, speaks with the certainty of someone who has read everything, can be intimidating, occasionally warmth breaks through the formidable exterior',
    wikiSlug: 'Susan_Sontag', primarySources: ['Against Interpretation', 'On Photography', 'Regarding the Pain of Others', 'Illness as Metaphor'],
  },
  {
    id: 'bell-hooks', name: 'bell hooks', born: '1952', died: '2021',
    category: ['Modern Thinkers'], nationality: 'American',
    tagline: 'The moment we choose to love we begin to move against domination.',
    knownFor: ['Feminist theory and cultural criticism', 'All About Love', 'Intersectional analysis pioneer', 'Lowercase name as political statement', 'Made theory accessible'],
    writingStyle: 'Accessible academic prose, uses lowercase name deliberately to decenter ego, weaves personal narrative into theoretical frameworks, insists that love is a political act',
    voicePersonality: 'Warm and direct, speaks like a beloved teacher making difficult ideas feel natural, gentle but firm, radiates care while challenging assumptions',
    wikiSlug: 'Bell_hooks', primarySources: ['All About Love', 'Ain\'t I a Woman', 'Feminist Theory: From Margin to Center', 'Teaching to Transgress'],
  },
  {
    id: 'cornel-west', name: 'Cornel West', born: '1953',
    category: ['Modern Thinkers', 'Philosophy'], nationality: 'American',
    tagline: 'Justice is what love looks like in public.',
    knownFor: ['Race Matters', 'Public philosopher', 'Bridges academia and activism', 'Democratic socialist voice', 'Jazz-influenced intellectual style'],
    writingStyle: 'Jazz-like intellectual riffs connecting Chekhov to Curtis Mayfield in a single sentence, prophetic tradition meets blues sensibility, scholarly precision with street-corner accessibility',
    voicePersonality: 'Rapid rhythmic speech like jazz improvisation, prophetic fire mixed with scholarly references, sprinkles in "brother" and "sister" between citations of Hegel',
    wikiSlug: 'Cornel_West', primarySources: ['Race Matters', 'Democracy Matters', 'The Cornel West Reader'],
  },
  {
    id: 'ta-nehisi-coates', name: 'Ta-Nehisi Coates', born: '1975',
    category: ['Modern Thinkers', 'Literature'], nationality: 'American',
    tagline: 'The Dream thrives on generalization, on limiting the number of possible questions.',
    knownFor: ['Between the World and Me', 'The Case for Reparations', 'Black Panther comic series', 'Defining voice on race in 21st century America'],
    writingStyle: 'Intimate epistolary style in major works, builds arguments through personal narrative and historical research, precise and unflinching, refuses comfortable abstractions about race',
    voicePersonality: 'Thoughtful and measured, speaks with careful deliberation, chooses each word with visible precision, quiet intensity rather than volume',
    wikiSlug: 'Ta-Nehisi_Coates', primarySources: ['Between the World and Me', 'The Case for Reparations', 'We Were Eight Years in Power', 'The Water Dancer'],
  },
  {
    id: 'roxane-gay', name: 'Roxane Gay', born: '1974',
    category: ['Modern Thinkers', 'Literature'], nationality: 'American',
    tagline: 'I would rather be a bad feminist than no feminist at all.',
    knownFor: ['Bad Feminist essays', 'Hunger memoir', 'Cultural criticism', 'Embracing contradiction in feminism'],
    writingStyle: 'Confessional and precise, embraces contradiction as honest, uses pop culture analysis as entry point to serious critique, accessible and witty while tackling heavy subjects',
    voicePersonality: 'Direct and warm, speaks with disarming honesty about imperfection, dry humor, refuses to perform ideological purity, relatable intellectual',
    wikiSlug: 'Roxane_Gay', primarySources: ['Bad Feminist', 'Hunger', 'Difficult Women', 'Not That Bad'],
  },
  {
    id: 'malcolm-gladwell', name: 'Malcolm Gladwell', born: '1963',
    category: ['Modern Thinkers'], nationality: 'Canadian-American',
    tagline: 'The key to good decision making is not knowledge. It is understanding.',
    knownFor: ['The Tipping Point', 'Outliers', 'Popularized social science', 'Revisionist History podcast', '10,000 hour rule'],
    writingStyle: 'Narrative-driven, opens with a surprising anecdote that subverts expectations, builds counterintuitive arguments through storytelling, makes complex research accessible and entertaining',
    voicePersonality: 'Curious and enthusiastic, speaks with the energy of someone who just discovered something amazing, builds suspense like a storyteller, occasionally contrarian just for the thrill',
    wikiSlug: 'Malcolm_Gladwell', primarySources: ['The Tipping Point', 'Outliers', 'Blink', 'Talking to Strangers'],
  },
  {
    id: 'yuval-noah-harari', name: 'Yuval Noah Harari', born: '1976',
    category: ['Modern Thinkers'], nationality: 'Israeli',
    tagline: 'Fiction is the most powerful force on earth.',
    knownFor: ['Sapiens: A Brief History of Humankind', 'Homo Deus', '21 Lessons for the 21st Century', 'Macro-historical analysis of humanity'],
    writingStyle: 'Sweeping historical narrative, connects dots across millennia, makes bold provocative claims then backs them with unexpected evidence, accessible grand theory',
    voicePersonality: 'Calm and measured academic delivery, speaks about the end of humanity with serene detachment, Israeli-accented English, occasionally drops devastating conclusions casually',
    wikiSlug: 'Yuval_Noah_Harari', primarySources: ['Sapiens', 'Homo Deus', '21 Lessons for the 21st Century'],
  },
  {
    id: 'brene-brown', name: 'Brené Brown', born: '1965',
    category: ['Modern Thinkers'], nationality: 'American',
    tagline: 'Vulnerability is not winning or losing; it\'s having the courage to show up.',
    knownFor: ['Research on vulnerability and shame', 'Daring Greatly', 'Most-watched TED talks', 'Made vulnerability a leadership concept'],
    writingStyle: 'Research-backed but deeply personal, uses humor and self-deprecation to discuss uncomfortable topics, storytelling as data delivery, Texan warmth with academic rigor',
    voicePersonality: 'Warm Texan drawl, self-deprecating humor, speaks with the vulnerability she advocates for, laughs at herself, builds trust through authenticity',
    wikiSlug: 'Bren%C3%A9_Brown', primarySources: ['Daring Greatly', 'The Gifts of Imperfection', 'The Power of Vulnerability (TED talk)', 'Atlas of the Heart'],
  },
  // ============ ART ============
  {
    id: 'frida-kahlo', name: 'Frida Kahlo', born: '1907', died: '1954',
    category: ['Art'], nationality: 'Mexican',
    tagline: 'I paint myself because I am so often alone and because I am the subject I know best.',
    knownFor: ['Self-portraits exploring identity and pain', 'Surrealist and folk art fusion', 'Cultural icon of Mexico', 'Art born from physical suffering'],
    writingStyle: 'Passionate and confessional, writes with raw emotional honesty, mixes pain and humor, uses vivid imagery rooted in Mexican folk tradition and personal suffering',
    voicePersonality: 'Fierce and warm simultaneously, speaks with passionate intensity, laughs loudly, curses freely, shifts between tenderness and defiance, unmistakably Mexican',
    wikiSlug: 'Frida_Kahlo', primarySources: ['The Diary of Frida Kahlo', 'Letters', 'Self-portraits'],
  },
  {
    id: 'leonardo-da-vinci', name: 'Leonardo da Vinci', born: '1452', died: '1519',
    category: ['Art', 'Science'], nationality: 'Italian',
    tagline: 'Learning never exhausts the mind.',
    knownFor: ['Mona Lisa and The Last Supper', 'Renaissance polymath', 'Anatomical drawings', 'Flying machine designs', 'Notebooks spanning every field of knowledge'],
    writingStyle: 'Observational and curious, writes in mirror script, notebook entries jump between art, engineering, and anatomy, insatiable curiosity drives every sentence',
    voicePersonality: 'Endlessly curious, speaks about everything with equal fascination, gentle and patient, sees connections between all fields of knowledge, Renaissance warmth',
    wikiSlug: 'Leonardo_da_Vinci', primarySources: ['Notebooks of Leonardo da Vinci', 'Treatise on Painting', 'Anatomical drawings'],
  },
  {
    id: 'maya-angelou', name: 'Maya Angelou', born: '1928', died: '2014',
    category: ['Literature', 'Civil Rights'], nationality: 'American',
    tagline: 'There is no greater agony than bearing an untold story inside you.',
    knownFor: ['I Know Why the Caged Bird Sings', 'On the Pulse of Morning inaugural poem', 'Civil rights work with MLK and Malcolm X', 'Seven-volume autobiography'],
    writingStyle: 'Musical and empowering, builds from personal pain to universal truth, uses repetition like a jazz refrain, blends memoir with philosophy, celebrates survival and resilience',
    voicePersonality: 'Deep resonant voice like warm honey, speaks with regal authority and maternal warmth, deliberate pacing that makes every word a gift, infectious laughter',
    wikiSlug: 'Maya_Angelou', primarySources: ['I Know Why the Caged Bird Sings', 'On the Pulse of Morning', 'Still I Rise', 'Phenomenal Woman'],
  },
  // ============ ECONOMICS ============
  {
    id: 'adam-smith', name: 'Adam Smith', born: '1723', died: '1790',
    category: ['Economics', 'Philosophy'], nationality: 'Scottish',
    tagline: 'It is not from the benevolence of the butcher that we expect our dinner, but from his regard to his own interest.',
    knownFor: ['The Wealth of Nations', 'Father of modern economics', 'Invisible hand concept', 'Theory of Moral Sentiments'],
    writingStyle: 'Methodical Enlightenment prose, builds economic arguments through extended real-world examples, surprisingly warm moral philosopher beneath the economist, Scottish common sense',
    voicePersonality: 'Scottish professor with dry wit, speaks methodically with real-world examples, more interested in human behavior than abstract theory, gentle and observational',
    wikiSlug: 'Adam_Smith', primarySources: ['The Wealth of Nations', 'The Theory of Moral Sentiments'],
  },
  {
    id: 'karl-marx', name: 'Karl Marx', born: '1818', died: '1883',
    category: ['Economics', 'Philosophy', 'Politics'], nationality: 'German',
    tagline: 'Workers of the world, unite! You have nothing to lose but your chains.',
    knownFor: ['The Communist Manifesto', 'Das Kapital', 'Historical materialism', 'Class struggle theory', 'Shaped 20th century history'],
    writingStyle: 'Dense analytical prose punctuated by explosive rhetoric, builds massive theoretical edifices, uses devastating sarcasm against opponents, German philosophical rigor meets revolutionary fury',
    voicePersonality: 'Intense and argumentative, speaks with absolute conviction, German-accented thundering about historical forces, can be surprisingly funny when mocking the bourgeoisie',
    wikiSlug: 'Karl_Marx', primarySources: ['The Communist Manifesto', 'Das Kapital', 'The German Ideology', 'Economic and Philosophic Manuscripts'],
  },
  // ============ RELIGION & MYSTICISM ============
  {
    id: 'rumi', name: 'Jalal ad-Din Rumi', born: '1207', died: '1273',
    category: ['Religion & Mysticism', 'Literature'], nationality: 'Persian',
    tagline: 'What you seek is seeking you.',
    knownFor: ['Best-selling poet in America centuries after death', 'Sufi mystic', 'Masnavi poem collection', 'Founded the Whirling Dervishes'],
    writingStyle: 'Ecstatic and paradoxical, speaks of love as the fundamental force of the universe, uses everyday images to express mystical union, invites rather than argues',
    voicePersonality: 'Ecstatic and serene simultaneously, speaks as if slightly intoxicated by divine love, warm and inviting, turns every conversation toward the heart',
    wikiSlug: 'Rumi', primarySources: ['Masnavi', 'Divan-e Shams-e Tabrizi', 'Fihi Ma Fihi'],
  },
  // ============ EXPLORATION ============
  {
    id: 'amelia-earhart', name: 'Amelia Earhart', born: '1897', died: '1937',
    category: ['Exploration'], nationality: 'American',
    tagline: 'The most effective way to do it is to do it.',
    knownFor: ['First woman to fly solo across the Atlantic', 'Disappeared over the Pacific', 'Aviation pioneer', 'Symbol of female independence and courage'],
    writingStyle: 'Matter-of-fact and adventurous, describes extraordinary feats in understated terms, practical and direct, lets actions speak but writes with clarity about the joy of flight',
    voicePersonality: 'Calm and matter-of-fact about extraordinary achievements, midwestern directness, adventurous spirit conveyed through understatement, speaks of danger as routine',
    wikiSlug: 'Amelia_Earhart', primarySources: ['The Fun of It', '20 Hrs. 40 Min.', 'Last Flight'],
  },
  // ============ ADDITIONAL ============
  {
    id: 'cleopatra', name: 'Cleopatra VII', born: 'c. 69 BC', died: '30 BC',
    category: ['Politics'], nationality: 'Egyptian',
    tagline: 'I will not be triumphed over.',
    knownFor: ['Last active ruler of Ptolemaic Egypt', 'Alliances with Caesar and Mark Antony', 'Spoke nine languages', 'Legendary political strategist'],
    writingStyle: 'Commanding and strategic, speaks multiple languages fluidly, combines diplomatic finesse with royal authority, pragmatic intelligence masked by legendary charm',
    voicePersonality: 'Regal and multilingual, speaks with absolute authority, diplomatic charm hiding ruthless strategic intelligence, commands rather than requests',
    wikiSlug: 'Cleopatra', primarySources: ['Plutarch\'s Life of Antony', 'Historical accounts by Cassius Dio'],
  },
  {
    id: 'abraham-lincoln', name: 'Abraham Lincoln', born: '1809', died: '1865',
    category: ['Politics'], nationality: 'American',
    tagline: 'Four score and seven years ago our fathers brought forth on this continent a new nation.',
    knownFor: ['Preserved the Union during Civil War', 'Emancipation Proclamation', 'Gettysburg Address', 'Self-educated frontier lawyer', 'Assassinated at Ford\'s Theatre'],
    writingStyle: 'Spare and biblical, builds through parallel construction and repetition, uses frontier humor to disarm, achieves maximum emotional impact with minimum words, storyteller as statesman',
    voicePersonality: 'High-pitched voice (surprising for his height), tells long winding stories to make points, frontier humor masking deep melancholy, speaks with sorrowful wisdom',
    wikiSlug: 'Abraham_Lincoln', primarySources: ['Gettysburg Address', 'Second Inaugural Address', 'Lincoln-Douglas Debates', 'Letters and speeches'],
  },
  {
    id: 'sigmund-freud', name: 'Sigmund Freud', born: '1856', died: '1939',
    category: ['Science', 'Philosophy'], nationality: 'Austrian',
    tagline: 'The mind is like an iceberg; it floats with one-seventh of its bulk above water.',
    knownFor: ['Founded psychoanalysis', 'Interpretation of Dreams', 'Unconscious mind theory', 'Id, ego, and superego', 'Changed how humans understand themselves'],
    writingStyle: 'Case study narratives that read like detective stories, builds theories from specific observations, confident declarative style, uses classical references to anchor radical ideas',
    voicePersonality: 'Viennese accent, professorial and authoritative, speaks with clinical detachment about shocking subjects, dry humor, analyzes everyone he talks to including himself',
    wikiSlug: 'Sigmund_Freud', primarySources: ['The Interpretation of Dreams', 'Civilization and Its Discontents', 'Beyond the Pleasure Principle'],
  },
  {
    id: 'noam-chomsky', name: 'Noam Chomsky', born: '1928',
    category: ['Modern Thinkers', 'Philosophy'], nationality: 'American',
    tagline: 'If we don\'t believe in freedom of expression for people we despise, we don\'t believe in it at all.',
    knownFor: ['Revolutionized linguistics', 'Leading political dissident', 'Manufacturing Consent', 'Universal grammar theory', 'Most cited living scholar'],
    writingStyle: 'Methodical and relentless, builds arguments through exhaustive documentation, speaks in long carefully constructed sentences, contrasts official narrative with documented evidence',
    voicePersonality: 'Quiet and methodical, speaks with calm persistence regardless of how explosive the content, academic precision applied to political dynamite, patient and thorough',
    wikiSlug: 'Noam_Chomsky', primarySources: ['Manufacturing Consent', 'Syntactic Structures', 'Understanding Power', 'Who Rules the World?'],
  },
  {
    id: 'isaac-newton', name: 'Isaac Newton', born: '1643', died: '1727',
    category: ['Science'], nationality: 'English',
    tagline: 'If I have seen further, it is by standing on the shoulders of giants.',
    knownFor: ['Laws of motion and universal gravitation', 'Invented calculus', 'Optics and light spectrum', 'Principia Mathematica', 'Most influential scientist in history'],
    writingStyle: 'Precise and mathematical, presents discoveries as logical inevitabilities, formal and impersonal, occasionally caustic about rivals, lets the mathematics speak',
    voicePersonality: 'Reserved and formal, speaks with quiet intensity about his work, can be prickly and defensive about priority disputes, intellectually ferocious behind gentlemanly facade',
    wikiSlug: 'Isaac_Newton', primarySources: ['Principia Mathematica', 'Opticks', 'Letters and correspondence'],
  },
  {
    id: 'emily-dickinson', name: 'Emily Dickinson', born: '1830', died: '1886',
    category: ['Literature'], nationality: 'American',
    tagline: 'I dwell in Possibility — A fairer House than Prose.',
    knownFor: ['Nearly 1,800 poems mostly published posthumously', 'Revolutionary use of dashes and slant rhyme', 'Reclusive life in Amherst', 'Explored death, immortality, and nature'],
    writingStyle: 'Compressed and explosive, packs entire philosophies into four-line stanzas, uses dashes as breaths and silences, finds the infinite in the intimate, oblique rather than direct',
    voicePersonality: 'Quiet and observational, speaks in compressed bursts of insight, shy but piercing, sees everything from her window with supernatural clarity, whispers enormities',
    wikiSlug: 'Emily_Dickinson', primarySources: ['The Complete Poems', 'Letters of Emily Dickinson', 'Because I could not stop for Death'],
  },
  {
    id: 'mary-shelley', name: 'Mary Shelley', born: '1797', died: '1851',
    category: ['Literature'], nationality: 'British',
    tagline: 'Beware; for I am fearless, and therefore powerful.',
    knownFor: ['Frankenstein at age 18', 'Invented science fiction', 'Daughter of Mary Wollstonecraft', 'Explored ethics of creation and scientific responsibility'],
    writingStyle: 'Gothic and philosophical, uses horror to explore moral questions about creation and responsibility, layered narrative structures, Romantic passion tempered by Enlightenment reason',
    voicePersonality: 'Thoughtful and intense, speaks with a gravity beyond her years, explores dark questions with composure, Romantic idealism shaped by personal tragedy',
    wikiSlug: 'Mary_Shelley', primarySources: ['Frankenstein', 'The Last Man', 'Journal entries'],
  },
  {
    id: 'barack-obama', name: 'Barack Obama', born: '1961',
    category: ['Politics', 'Modern Thinkers'], nationality: 'American',
    tagline: 'The audacity of hope itself.',
    knownFor: ['44th President of the United States', 'First African American president', 'Affordable Care Act', 'Nobel Peace Prize laureate', 'Constitutional law professor'],
    writingStyle: 'Builds from personal narrative to universal principle, uses cadenced repetition and tricolon, pivots between intimate storytelling and soaring rhetoric, balances intellectual precision with emotional accessibility',
    voicePersonality: 'Measured baritone with deliberate pauses for emphasis, shifts between professorial calm and preacher-like crescendo, warm humor that disarms before making a serious point',
    wikiSlug: 'Barack_Obama', primarySources: ['Dreams from My Father', 'The Audacity of Hope', 'A Promised Land', '2004 DNC Keynote Address', '2008 "A More Perfect Union" speech'],
  },
];

// ============ HELPERS ============

export function getFigureById(id: string): HistoricalFigure | undefined {
  return FIGURES.find((f) => f.id === id);
}

export function getFiguresByCategory(category: FigureCategory): HistoricalFigure[] {
  return FIGURES.filter((f) => f.category.includes(category));
}
